name: Run Linting

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version: '1.23.5'

      - name: Install Golint
        run: |
          go install golang.org/x/lint/golint@latest

      - name: Run Golint
        run: |
          golint ./...
