name: Run Tests

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version: '1.23.5'

      - name: Download Go modules
        run: go mod download

      - name: Run tests
        run: go test ./... -v
