name: Auto Versioning

on:
  push:
    tags:
      - 'v*'

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version: '1.23.5'
